name: cs598 # conda env create -f environment.yml
channels:
  - pytorch
  - huggingface
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10   # or the Python version you prefer
  - pip
  - pip:
    - -r requirements.txt
# requirements.txt
# PyTorch with CUDA support (replace 'cpuonly' with 'cudatoolkit=11.1' if you have GPU)
#torch==1.9.0+cpu
# NumPy
#numpy==1.21.1
# scikit-learn
#scikit-learn==0.24.2
# Matplotlib
# TensorBoard (compatible with PyTorch)
#torch==1.9.0+cu111
#torchvision==0.10.0+cu111
#torchaudio==0.9.0
#torch==2.1.0+cu118
#torchvision==0.16.0+cu118
#torchaudio==2.1.0